service: web-training-nest

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  # - serverless-localstack
  # - serverless-plugin-warmup

custom:
  localstack:
    stages:
      - local
    lambda:
      mountCode: True
    docker:
      sudo: False
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging

provider:
  name: aws
  runtime: nodejs18.x

package:
  individually: true

functions:
  main:
    # handler: src/main.handler
    handler: src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    # events:
    #   - http:
    #       method: any
    #       path: /{proxy+}
